# This GitHub action can generate binaries for the PR and upload them for future use
name: Generate binaries on PR
on:
  pull_request:
    branches:
      - master
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --snapshot
      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: terraform-provider-outscale
          path: dist/terraform-provider-outscale*
